apiVersion: v1

kind: Service

metadata:

   name: leon-service

spec:

   type: NodePort

   selector:

      app: leon

   ports:

      - protocol: TCP

        port: 2020

        targetPort: 80

        nodePort: 30020
